import './header';
import './authorization-window';
import './mobile-menu';
import './all-categories';
import './support-ukraine';
import './modal-window';
import './loader';
import './scroll-up';
import './shopping-list';
