import * as firebaseService from './firebase-services';
import * as header from './header';
import * as authorizationWindow from './authorization-window';
import * as modalWindow from './modal-window';
import * as mobileMenu from './mobile-menu';
import * as allCategories from './all-categories';
import * as supportUkraine from './support-ukraine';
import * as listOfBooks from './list-of-books';
// import * as shoppingList from './shopping-list';
import * as pagination from './pagination';
import * as loader from './loader';
import * as scrollUp from './scroll-up';
